

spring.application.name=Spring-thymeleaf-mvc-crud-form-code

server.port=9000

education= Hight_School , University , Master


spring.datasource.url=jdbc:mysql://localhost:3306/employee_directoryy
spring.datasource.username=springstudent
spring.datasource.password=springstudent
